# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TfManage2Dev < Formula
  desc "Terraform workspace manager with enhanced CI/CD detection and interactive commands (development version)"
  homepage "https://github.com/sorinlg/tf-manage2"
  version "0.5.0-rc.0"
  license "MIT"

  depends_on "terraform" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sorinlg/tf-manage2/releases/download/v0.5.0-rc.0/tf-manage2_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "2784798b7f50d88fb32708c3b39dc5fa5dd8787819f9385a107b889ec4f322c9"

      def install
        bin.install "tf"
        bash_completion.install "bin/tf_complete.sh" => "tf"
        zsh_completion.install "bin/tf_complete.zsh" => "_tf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sorinlg/tf-manage2/releases/download/v0.5.0-rc.0/tf-manage2_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "3feafab0bbf6818fa76eac270d7ee2bc1387946abd392570351d72448960f9cc"

      def install
        bin.install "tf"
        bash_completion.install "bin/tf_complete.sh" => "tf"
        zsh_completion.install "bin/tf_complete.zsh" => "_tf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/sorinlg/tf-manage2/releases/download/v0.5.0-rc.0/tf-manage2_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "a32298ef26010d4840559f2ff6e65de4a6410f68a8aa7c091dd4936eaef8589c"
      def install
        bin.install "tf"
        bash_completion.install "bin/tf_complete.sh" => "tf"
        zsh_completion.install "bin/tf_complete.zsh" => "_tf"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/sorinlg/tf-manage2/releases/download/v0.5.0-rc.0/tf-manage2_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "20a0222686f9152e77f475293d39e3948423dfa4464840bcacc9dc7fddf3835a"
      def install
        bin.install "tf"
        bash_completion.install "bin/tf_complete.sh" => "tf"
        zsh_completion.install "bin/tf_complete.zsh" => "_tf"
      end
    end
  end

  test do
    system "#{bin}/tf", "--help"
  end
end
