# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TfManage2Dev < Formula
  desc "Terraform workspace manager with enhanced CI/CD detection and interactive commands (development version)"
  homepage "https://github.com/sorinlg/tf-manage2"
  version "0.5.0-rc.0"
  license "MIT"

  depends_on "terraform" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sorinlg/tf-manage2/releases/download/v0.5.0-rc.0/tf-manage2_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "abd4127b87277b4514fd05c0f88ef29028b390c811e206538b37624e8b9082ce"

      def install
        bin.install "tf"
        bash_completion.install "bin/tf_complete.sh" => "tf"
        zsh_completion.install "bin/tf_complete.zsh" => "_tf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sorinlg/tf-manage2/releases/download/v0.5.0-rc.0/tf-manage2_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "dc975b10332264fea8c63c0556e973caf27461106535fe5eac8ca2998a57c2fb"

      def install
        bin.install "tf"
        bash_completion.install "bin/tf_complete.sh" => "tf"
        zsh_completion.install "bin/tf_complete.zsh" => "_tf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/sorinlg/tf-manage2/releases/download/v0.5.0-rc.0/tf-manage2_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "62cc206288aca195ec47577116dd89ff25cbdf62a0dd1e044605ec455fa7a91a"
      def install
        bin.install "tf"
        bash_completion.install "bin/tf_complete.sh" => "tf"
        zsh_completion.install "bin/tf_complete.zsh" => "_tf"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/sorinlg/tf-manage2/releases/download/v0.5.0-rc.0/tf-manage2_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d9daa34cddc9ec7d55f3a07f38408f3ccaf4ce80069b53a7e491fecf7bc5806f"
      def install
        bin.install "tf"
        bash_completion.install "bin/tf_complete.sh" => "tf"
        zsh_completion.install "bin/tf_complete.zsh" => "_tf"
      end
    end
  end

  test do
    system "#{bin}/tf", "--help"
  end
end
