# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TfManage2Dev < Formula
  desc "Terraform workspace manager with enhanced CI/CD detection"
  homepage "https://github.com/sorinlg/tf-manage2"
  version "0.9.1-rc.0"
  license "MIT"

  depends_on "terraform" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sorinlg/tf-manage2/releases/download/v0.9.1-rc.0/tf-manage2_Darwin_x86_64.tar.gz"
      sha256 "f1c1efb27c7f68784c570ac1b17e3a0494c7e78e509c8224e225f6fe91ad5b84"

      def install
        bin.install "tf"
        bash_completion.install "bin/tf_complete.sh" => "tf"
        zsh_completion.install "bin/tf_complete.zsh" => "_tf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sorinlg/tf-manage2/releases/download/v0.9.1-rc.0/tf-manage2_Darwin_arm64.tar.gz"
      sha256 "aae67f8e9505bdd7d335a74b1d637dd3efc449c3d7f11ba08571be0108a809a3"

      def install
        bin.install "tf"
        bash_completion.install "bin/tf_complete.sh" => "tf"
        zsh_completion.install "bin/tf_complete.zsh" => "_tf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorinlg/tf-manage2/releases/download/v0.9.1-rc.0/tf-manage2_Linux_x86_64.tar.gz"
      sha256 "5bf13c51c3cbc684e43bc5a4f0273f6e16859932107b530f3b90278d01e0576a"
      def install
        bin.install "tf"
        bash_completion.install "bin/tf_complete.sh" => "tf"
        zsh_completion.install "bin/tf_complete.zsh" => "_tf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorinlg/tf-manage2/releases/download/v0.9.1-rc.0/tf-manage2_Linux_arm64.tar.gz"
      sha256 "7affcb0a47af978ce1b0108874b14c72442e7b770289c458afceb5bb14a3243a"
      def install
        bin.install "tf"
        bash_completion.install "bin/tf_complete.sh" => "tf"
        zsh_completion.install "bin/tf_complete.zsh" => "_tf"
      end
    end
  end

  test do
    system "#{bin}/tf", "--help"
  end
end
