# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TfManage2Dev < Formula
  desc "Terraform workspace manager with enhanced CI/CD detection"
  homepage "https://github.com/sorinlg/tf-manage2"
  version "0.8.1-rc.1"
  license "MIT"

  depends_on "terraform" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sorinlg/tf-manage2/releases/download/v0.8.1-rc.1/tf-manage2_Darwin_x86_64.tar.gz"
      sha256 "8dcc6dfe48a61212041492e03476dca631863c4d2365c74716ee09d54cdb9eab"

      def install
        bin.install "tf"
        bash_completion.install "bin/tf_complete.sh" => "tf"
        zsh_completion.install "bin/tf_complete.zsh" => "_tf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sorinlg/tf-manage2/releases/download/v0.8.1-rc.1/tf-manage2_Darwin_arm64.tar.gz"
      sha256 "8a8145c384f4a540ded0157481375a11300a7bc529fb51a41578a8626f3023d7"

      def install
        bin.install "tf"
        bash_completion.install "bin/tf_complete.sh" => "tf"
        zsh_completion.install "bin/tf_complete.zsh" => "_tf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/sorinlg/tf-manage2/releases/download/v0.8.1-rc.1/tf-manage2_Linux_x86_64.tar.gz"
      sha256 "626b300b7beff317b7746989d24bba96cfbd1e6b1d9bb55ca96164fe1faccb58"
      def install
        bin.install "tf"
        bash_completion.install "bin/tf_complete.sh" => "tf"
        zsh_completion.install "bin/tf_complete.zsh" => "_tf"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/sorinlg/tf-manage2/releases/download/v0.8.1-rc.1/tf-manage2_Linux_arm64.tar.gz"
      sha256 "7ae99ada5c71dbc550749ed95ebc15f1423786788364b53eb4561236d1615595"
      def install
        bin.install "tf"
        bash_completion.install "bin/tf_complete.sh" => "tf"
        zsh_completion.install "bin/tf_complete.zsh" => "_tf"
      end
    end
  end

  test do
    system "#{bin}/tf", "--help"
  end
end
